<footer class="logo-and-appicons">
  <p><strong>Download the App</strong>
    <img src="images/android-brands-solid.svg" alt="Android"></img>
    <img src="images/apple-brands-solid.svg" alt="Apple"></img>
  </p>

    <div class="appicons">
      <a
      href="https://www.facebook.com/mam.man.948494?mibextid=wwXIfr&rdid=yAqTP6CN8SHfQtMB&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2F17GbHqWPLY%2F%3Fmibextid%3DwwXIfr#"><img class="fb" src="images/facebook-brands-solid.svg"alt="Facebook"></a>
      <a href="https://x.com/swinburne"><img class="x" src="images/x-twitter-brands-solid.svg" alt="X"></img></a>
      <a href="https://www.youtube.com/@AquibRahmani"><img class="yt" src="images/youtube-brands-solid.svg" alt="YouTube"></a>
      <a href="https://www.instagram.com/swinburne/"><img class="ig" src="images/instagram-brands-solid.svg" alt="Instagram"></a>
      <a href="https://www.tiktok.com/@david.webdeveloper?is_from_webapp=1&sender_device=pc"><img class="tiktok" src="images/tiktok-brands-solid.svg" alt="TikTok"></a>
      <a href="https://nguyenhungthinh.atlassian.net/jira/software/projects/SCRUM/summary"><img class="jira" src="images/jira-brands-solid.svg" alt="Jira"></a>
    </div>
    <div class="ending-section">
      <hr class="end-line">
      <div class="end-text">
        <p>Browse by:Companies Jobs Locations Communities Recent Posts</p>
        <p>Copyright © 2008-2025. <span class="highlight"><strong>Webtech</strong></span> LLC. "Webtech," "Worklife
          Pro,"
          "Bowls," and logo are proprietary trademarks
          of Webtech.</p>
      </div>
    </div>
  </footer>